# Generated by Django 5.0.6 on 2026-06-18 03:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('ELECTRONICS', '📱 Electronics'), ('BOOKS', '📚 Books & Stationery'), ('ID_CARDS', '\U0001faaa ID Cards & Documents'), ('BAGS', '🎒 Bags & Luggage'), ('CLOTHING', '👕 Clothing & Accessories'), ('KEYS', '🔑 Keys & Keychains'), ('OTHER', '📦 Other')], default='OTHER', max_length=20)),
                ('status', models.CharField(choices=[('LOST', '🟢 Lost'), ('FOUND', '🔵 Found'), ('RESOLVED', '✅ Resolved')], default='LOST', max_length=20)),
                ('building', models.CharField(max_length=100)),
                ('room', models.CharField(blank=True, max_length=50, null=True)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('date_occurred', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('color', models.CharField(blank=True, max_length=50)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_details', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('views_count', models.IntegerField(default=0)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['-date_reported'],
            },
        ),
    ]
